### ISSUE TITLE
Undefined values in proto maps

### ISSUE THREAD

**Issue by tiagopog** [tomas-abrahamsson/gpb#111]
Hey there,

I'm currently working on a [PR](https://github.com/bitwalker/exprotobuf/pull/73) for the `exprotobuf` lib in which I'm bringing new fatures from `gpb` like the use of `gpb_compile:file/2`, the  `mapfields_as_maps` option among others.

I'm pretty close to finish the work there but I got stuck in one point: when using the `mapfields_as_maps` option for maps with string keys/values (`map<string, string>`) and then trying to pass a `nil` value, it breaks the encoding.

For the given proto:

```proto
message User {
  string name = 1;
  map<string, string> errors = 2;
}
```

I get the following error:

```elixir
> :user.encode_msg({:User, "Tiago", %{"foo" => :undefined}})
** (ArgumentError) argument error
             (stdlib) :unicode.characters_to_binary(:undefined)
    (exprotobuf_demo) /app/priv/gpb_records/user.erl:95: :user.e_type_string/2
    (exprotobuf_demo) /app/priv/gpb_records/user.erl:67: :user.e_mfield_User_errors/3
    (exprotobuf_demo) /app/priv/gpb_records/user.erl:75: :user.e_field_User_errors/3
```

However, if `name` (also a string field) is passed as `undefined` it works properly:

```elixir
> :user.encode_msg({:User, :undefined, %{"foo" => "bar"}})
<<18, 10, 10, 3, 102, 111, 111, 18, 3, 98, 97, 114>>
```

That error above references the following part of the Erlang-generated record's code:

```erlang
'e_msg_map<string,string>'(#{key := F1, value := F2},
			   Bin, TrUserData) ->
    B1 = begin
	   TrF1 = id(F1, TrUserData),
	   e_type_string(TrF1, <<Bin/binary, 10>>)
	 end,
    begin
      TrF2 = id(F2, TrUserData),
      e_type_string(TrF2, <<B1/binary, 18>>)
    end.

e_type_string(S, Bin) ->
   %% The error happens here:
    Utf8 = unicode:characters_to_binary(S),
    Bin2 = e_varint(byte_size(Utf8), Bin),
    <<Bin2/binary, Utf8/binary>>.
```

I poked the code a bit more and saw that there are some checks for this `undefined` use case only for the `name` field:

```erlang
e_msg_User(#'User'{name = F1, errors = F2}, Bin,
	   TrUserData) ->
    B1 = if F1 == undefined -> Bin;
	    true ->
		begin
		  TrF1 = id(F1, TrUserData),
		  e_type_string(TrF1, <<Bin/binary, 10>>)
		end
	 end,
    begin
      TrF2 = 'tr_encode_User.errors'(F2, TrUserData),
      if TrF2 == [] -> B1;
	 true -> e_field_User_errors(TrF2, B1, TrUserData)
      end
    end.

%% ...

merge_msg_User(#'User'{name = PFname,
		       errors = PFerrors},
	       #'User'{name = NFname, errors = NFerrors},
	       TrUserData) ->
    #'User'{name =
		if NFname =:= undefined -> PFname;
		   true -> NFname
		end,
	    errors =
		'tr_merge_User.errors'(PFerrors, NFerrors, TrUserData)}.

%% ...

-dialyzer({nowarn_function,v_msg_User/3}).
v_msg_User(#'User'{name = F1, errors = F2}, Path,
	   TrUserData) ->
    if F1 == undefined -> ok;
       true -> v_type_string(F1, [name | Path])
    end,
    'v_map<string,string>'(F2, [errors | Path], TrUserData),
    ok.
```

Am I missing something? Any ideia on how should I work around this?

Thanks and cheers!

**Comment by tomas-abrahamsson** [comment]
That use of `map<_,_>` had entirely evaded my attention, but I see now that the [backwards compatibility definition in the protobuf language guide](https://developers.google.com/protocol-buffers/docs/proto#maps) has both key and value as `optional`. The [definition that gpb uses](https://github.com/tomas-abrahamsson/gpb/blob/3.27.2/src/gpb.erl#L1159-L1164) is `required`, which is wrong. This is used also [from `gpb_compile`](https://github.com/tomas-abrahamsson/gpb/blob/3.27.2/src/gpb_compile.erl#L1704-L1707)   This essentially means passing a `nil` value in a `map<_,_>` is currently not supported, but it should be, so this is a bug.

However, changing from `required` to `optional` also implies reworking [the code that translates these implicit message types to either 2-tuple lists, or to maps.](https://github.com/tomas-abrahamsson/gpb/blob/3.27.2/src/gpb_compile.erl#L5827-L5919) It currently assumes both key and value always exists. There are a two cases for `mapfields_as_maps`, depending on if `maps_unset_optional` is `present_undefined` (default) or `omitted`.

I'll look into it, but it might be a little while.

**Comment by tiagopog** [comment]
Thank you for the clear explanation.

Just one thing a didn't get: did you mean that using `{:maps_unset_optional, :present_undefined}` I can achieve the proper encoding without any internal error?

If so, I tried recompiling the proto file with that option:

```elixir
> :gpb_compile.file('user.proto', [{:i, '/app/lib/'}, {:o, '/app/priv/gpb_records'}, :mapfields_as_maps,
 {:maps_unset_optional, :present_undefined}])
:ok
```

And encoding again:

```elixir
pry(2)> :user.encode_msg({:User, "Tiago", %{"foo" => :undefined}})
** (ArgumentError) argument error
             (stdlib) :unicode.characters_to_binary(:undefined)
    (exprotobuf_demo) /app/priv/gpb_records/user.erl:95: :user.e_type_string/2
    (exprotobuf_demo) /app/priv/gpb_records/user.erl:67: :user.e_mfield_User_errors/3
    (exprotobuf_demo) /app/priv/gpb_records/user.erl:75: :user.e_field_User_errors/3

pry(2)> :user.encode_msg({:User, "Tiago", %{"foo" => nil}})
** (ArgumentError) argument error
             (stdlib) :unicode.characters_to_binary(nil)
    (exprotobuf_demo) /app/priv/gpb_records/user.erl:95: :user.e_type_string/2
    (exprotobuf_demo) /app/priv/gpb_records/user.erl:67: :user.e_mfield_User_errors/3
    (exprotobuf_demo) /app/priv/gpb_records/user.erl:75: :user.e_field_User_errors/3
```

Did I miss something? What's the proper workaround (a code sample, if possible) for this issue?

**Comment by tomas-abrahamsson** [comment]
> did you mean with the use of `{:maps_unset_optional, :present_undefined}` I could achieve the proper encoding without any internal error?

No, sorry for being unclear. I meant only that just changing the internal definition in gpb is not enough, plus a reminder (to myself) about what to consider when updating the rest.

**Comment by tiagopog** [comment]
Got it. I'll add a caveat about this to the release notes of that PR.

**Comment by tomas-abrahamsson** [comment]
I just wrote some C++ and took Google's protoc out for a spin to see what happens when it decodes map fields with omitted keys or values. I used the following .proto file for decoding using the C++ protobuf library:
```protobuf
syntax="proto2";
message m1 {
  map<uint32,string> f = 1;
}
```
and I used the .proto file below, with compatible definitions, for encoding (from the Erlang side):
```protobuf
syntax="proto2";
message m1 {
  repeated UInt32ToStringMap f = 1;
}
message UInt32ToStringMap {
  optional uint32 k = 1;
  optional string v = 2;
}
```
This is what I got:
<table>
<tr>
<th>Encoded in Erlang</th>
<th>Resulted in this being decoded in C++</th>
<th>Comment</th>
</tr>
<tr>
<td><pre>
#{f => [#{k => 1, v => "abc"},
        #{k => 2, v => "def"}]}
</pre></td>
<td><pre>Read 18 octets
item: 2 -> "def"
item: 1 -> "abc"
</pre></td>
<td>As expected</td>
</tr>
<tr>
<td><pre>
#{f => [#{k => 1},
        #{k => 2, v => "def"}]}
</pre></td>
<td><pre>Read 13 octets
item: 2 -> "def"
item: 1 -> ""
</pre></td>
<td>Omitted string value defaults to <code>""</code></td>
</tr>
<tr>
<td><pre>
#{f => [#{v => "abc"},
        #{k => 2, v => "def"}]}
</pre></td>
<td><pre>Read 16 octets
item: 2 -> "def"
item: 0 -> "abc"
</pre></td>
<td>Omitted integer key defaults to <code>0</code></td>
</tr>
<tr>
<td><pre>
#{f => [#{},
        #{k => 2, v => "def"}]}
</pre></td>
<td><pre>Read 11 octets
item: 2 -> "def"
item: 0 -> ""
</pre></td>
<td>Both key and value type-defaults</td>
</tr>
</table>

This implies that even though using `syntax="proto2"`, omitted optional values get type-defaults, as if had it been `syntax="proto3"`.

I think this further implies that `undefined` should not be valid as key or value when specifying a `map<_,_>` value for encoding. (except of course if you have an enum as map value, with `undefined` as an enumerator) Thus, in your first example:
```elixir
> :user.encode_msg({:User, "Tiago", %{"foo" => :undefined}}) # would be invalid
> :user.encode_msg({:User, "Tiago", %{"foo" => ""}}) # would be ok
```

Apparently, with `gpb` there is a bug when decoding `map<_,_>` fields with such omitted keys or values. One gets `'$undef'` instead of the type default. I need to fix that.

**Comment by tiagopog** [comment]
Thanks for the detailed report, @tomas-abrahamsson. So for now, in the absence of a key/valeu, I'll stick with the zero/empty values that you mentioned above.

**Comment by tomas-abrahamsson** [comment]
FYI: I made an attempt at just treating `map<_,_>` fields internally as proto3-defined messages when generating decoders, thinking this would be a relatively clean way to solve things, but that didn't turn out as expected. I stumbled upon the fact that a sub-message in proto3 does not really have a default. So I checked to see what the C++ code does in this case.

Given
```protobuf
syntax="proto2";
message m1 {
  map<uint32,m2> f = 1;
}
message m2 {
  required string s = 3;
}
```
and its equivalent
```protobuf
syntax="proto2";
message m1 {
  repeated fmap f = 1;
}
message fmap {
  optional uint32 k=1;
  optional m2     v=2;
}
message m2 {
  required string s = 3;
}
```
I encoded `#{f => [#{k=>1}]}` and decoded this with the protobuf C++ libs+generated code. It said:
```
[libprotobuf ERROR google/protobuf/message_lite.cc:118] Can't parse message of type "m1" because it is missing required fields: f[0].value.s
```
This means the handling is a little bit more tricky and some `map<_,_>` fields are not so optional.

**Comment by tomas-abrahamsson** [comment]
I just pushed 3.27.4 handling this, hence closing (just re-open if there's anything). More specifically:
* On encoding, both keys and values are treated as required. I figure it does not really make sense to have a keys or values as undefined on the Erlang-internal level, and I guess the same goes for Google's protobuf in C++. (Although as an esoteric special-case, one could maybe consider a `map<_,_>` type fields with only keys, and all values omitted to be a set, but that's not handled)
* On encoding, if a key or value has a type-default value, it is still encoded, also with `syntax="proto3"`. (By type-default, I mean `0` for ints, `""` for strings and so on.) This is in contrast to other proto3 fields, but it is how Google's protobuf encoder seems to work.
* On decoding, if a key or value is missing, its type-default value is used instead. However, if the value is a sub message, then an error is raised, since there is no type-default for a sub message. (Only values can be sub messages, keys cannot)

**Comment by tiagopog** [comment]
Thanks for fixing and clarifying this topic :-)
