### ISSUE TITLE
Accepting pre-encoded messages as values

### ISSUE THREAD

**Issue by tsloughter** [tomas-abrahamsson/gpb#130]
I wanted to bring up a potential optimization, at least for our use case :).

We have protos that get encoded and written to a kafka like log. Often those are read back and passed to a client, this process involved decoding the message just to re-encode. Something like:

```
message Msg {
  ... stuff ...
}

message Response {
  repeated Msg messages = 1;
}
```

```erlang
Msgs = read_msgs(),
Decoded = [proto_pb:decode_msg(M, msg) || M <- Msgs],
{200, proto_pb:encode_msg(#{messages => Decoded}, response)}.
```

So I was thinking about how the encode step could simply keep the existing proto if it encounters it during encoding.

Curious of your thoughts. Would this be too inefficient to do such a check during encoding? Or too ugly to add as an optional check to include in the encode logic? Too niche of a use-case?

**Comment by tomas-abrahamsson** [comment]
If I remember correctly, the wire encoding of a message is identical to that of bytes; length delimited. So if you would want to do a quick try, you could have a separately compiled proto def on the reading-and-repacking side where the Msg is of type bytes instead of a message. For example if you would want to measure performance gains or so.

It would of course be a bit impractical to keep a full set parallel proto def files with just that change, bytes instead of Msg, but I'm thinking if one could expand the building a bit ad follows, it might perhaps be good for a first take: First get the defs on internal form by compiling with the to_proto_defs option, then modify the type of that element, then compile those slightly modified definitions to erl files, see gpb_compile:proto_defs/2, possibly with another module name suffix if you would want to have both sets of proto encoders/decoders available at runtime.

I think that could work, but can't try it out at the moment myself to verify (travelling)

**Comment by tomas-abrahamsson** [comment]
I've attached some proof-of-concept code that modifies type to `bytes`, then compiles to memory. Then `read_msgs` returns a list of binaries that are encoded first with the original protobuf codec (R0) and then with the modified protobuf codec (R1) and the results are the same.
```
62> xrepack:build_to_memory().
Defs0=[{{msg,msg},[{field,f,1,2,uint32,required,[]}]},
       {{msg,response},[{field,messages,1,2,{msg,msg},repeated,[]}]},
       {{msg_containment,"x"},[msg,response]}]
Defs1=[{{msg,msg},[{field,f,1,2,uint32,required,[]}]},
       {{msg,response},[{field,messages,1,2,bytes,repeated,[]}]},
       {{msg_containment,"x"},[msg,response]}]
ok
63> xrepack:test().
Msgs    = [<<8,1>>,<<8,2>>,<<8,3>>]
Decoded = [#{f => 1},#{f => 2},#{f => 3}]
R0 = {200,<<10,2,8,1,10,2,8,2,10,2,8,3>>}
R1 = {200,<<10,2,8,1,10,2,8,2,10,2,8,3>>}
```

[files.tar.gz](https://github.com/tomas-abrahamsson/gpb/files/1782105/files.tar.gz)

**Comment by tsloughter** [comment]
Very cool! I did consider just forcing the use of the `Any` type for any proto we wanted to ship around like that but the end users don't want that, so figured it might work as a potential optimization for all messages.

**Comment by tomas-abrahamsson** [comment]
Would this approach to change the types and generate a second set of codecs be a viable way forward for you? I think it would be a slightly more sane approach than an option (or so) to accept pre-encoded msgs or pre-encoded fields. For fields of type message, I think the approach ought to be pretty future-proof, I cannot see that the wire type could be changed without other major changes.

**Comment by tomas-abrahamsson** [comment]
I'll be closing the issue, just re-open if there's anything more to it!
