### ISSUE TITLE
Replace proplists:get_value/2 with lists:keyfind/3

### ISSUE THREAD

**Issue by lpgauth** [tomas-abrahamsson/gpb#153]
`lists:keyfind/3` is around 5x faster than `proplists:get_value/2`.

Quick benchmarks in my laptop:

```
computed 1000 random key searches on a 10000-sized list in 113.962 ms using proplists
computed 1000 random key searches on a 10000-sized list in 25.395 ms using lists
computed 1000 random key searches on a 100000-sized list in 999.113 ms using proplists
computed 1000 random key searches on a 100000-sized list in 202.334 ms using lists
computed 1000 random key searches on a 1000000-sized list in 9200.521 ms using proplists
computed 1000 random key searches on a 1000000-sized list in 2691.522 ms using lists
```

**Comment by tomas-abrahamsson** [comment]
Do you mean to use `lists:keyfind` instead of `proplists:get_value` in generated code to make encoding/decoding faster, or in the gpb compiler itself to speed up compilation? (Or both?)

If in the generated code: how much would it speed up? It is currently used for options, so common case is an empty list or a very-few-element list, since there is only at most two options (`verify` and `user_data`)

If in the gpb compiler itself: have you measured speedup, eg for a big proto file? From what I've measured earlier, if I remember correctly, about half of the time spent compiling a `.proto` to a `.erl` is turning the parse-trees to textual source (the call to `erl_prettypr:format`). It was some time ago, so I don't have the exact measurement at hand, but can maybe dig it up.

**Comment by lpgauth** [comment]
Hi Thomas, 
I re-ran the benchmarks for lookups in an empty list and you're right that the performance difference is negligible. I still think that doing the lookup is wasteful.

What I propose then is to expose the actual decoder / encoder NIF calls so we can skip the call to `proplists:get_value/2` entirely. 

e.g.

```erlang
{'InverseStvlist', Key, Value} = stvlist:decode_msg(Bin, 'InverseStvlist')
```
vs

```erlang
 {'InverseStvlist', Key, Value} = stvlist:d_msg_InverseStvlist(Bin)
```

Running benchmarks (10000 decodes of a small record) I get a 4083362/1725002 ~= 2.3X speed improvement.

You can see from the callgring output bellow that the call to proplist is quite costly (and also all the indirection).

<img width="616" alt="screen shot 2018-09-17 at 4 34 48 pm" src="https://user-images.githubusercontent.com/5488/45648876-bc7df700-ba97-11e8-9725-167863b9dd79.png">

**Comment by tomas-abrahamsson** [comment]
Hmm.. the `d_msg_<MsgName>` is a bit internal, and exposing it might impose limitations in the future. However, the `epb_functions` option is kind of half  of what you want. With
`gpb_compile:string(x, "message Mmm { required uint32 f = 1; }", [epb_functions, nif]).` the following is generated (slightly redacted for readability)

```erlang
-export([decode/2]). %% epb compatibility
-export([decode_Mmm/1]).
...
decode_msg(Bin, MsgName) when is_binary(Bin) ->
    decode_msg(Bin, MsgName, []).

decode_msg(Bin, MsgName, Opts) when is_binary(Bin) ->
    TrUserData = proplists:get_value(user_data, Opts),
    decode_msg_1_catch(Bin, MsgName, TrUserData).

... [ifdef wrapping redacted] ...
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch ...
    end.

decode_msg_2_doit('Mmm', Bin, TrUserData) ->
    id(d_msg_Mmm(Bin), TrUserData).

%% epb compatibility
decode(MsgName, Bin)
    when is_atom(MsgName), is_binary(Bin) ->
    decode_msg(Bin, MsgName).

decode_Mmm(Bin) when is_binary(Bin) ->
    decode_msg(Bin, 'Mmm').

d_msg_Mmm(Bin) ->
    erlang:nif_error({error, {nif_not_loaded, 'Mmm'}},
                     [Bin]).
```

If gpb was changed so that the `decode_Mmm` was rewired into the below, I guess you would get performance figures close to what you've measured, and the `d_msg_Mmm` functions would avoid exposure, would that be ok? I don't know if adding `-compile({inline,d_msg_Mmm/1}).` would have any measurable effect.

```erlang
decode_Mmm(Bin) when is_binary(Bin) ->
    d_msg_Mmm(Bin).
```

**Comment by lpgauth** [comment]
Hi, yes, that should work.

By the way, without the Erlang code `gpb` is as fast as `enif_protobuf`.

```
26214796 (enif_protobuf)
23833456 (GPB NIF d_msg_InverseStvlist/1)
83265895 (GPB NIF decode_msg/2)
```

**Comment by tomas-abrahamsson** [comment]
Hi, I pushed to a (temporary branch) `bypass-wrappers`. On this branch, there is a new option, `bypass_wrappers`. (I decided to go with a new option rather than the `epb_functions` since this option is incompatible with `maps`, and it seemed unfortunate to miss out on that.)

When this new option `bypass_wrappers` is specified, some more functions are exported: `Module:encode_msg_<MsgName>/1,2` and `Module:decode_msg_<MsgName>/1,2`. If `nif` is specified, then these functions are the nif  functions directly with nothing in between. The `/2` versions are not exported if `nif` is specified.

This branch also has the fixed `?OTP_RELEASE` macro handling we discussed in #154.

If this works well for you, I'll make a release of it.
