### ISSUE TITLE
Too big vcs diff even only one field change in proto file

### ISSUE THREAD

**Issue by suexcxine** [tomas-abrahamsson/gpb#160]
I changed only one field in my proto file,
When I regenerate using `protoc-erl`, there are thousands lines of code changes..
(Both git and svn shows large diff),
Although I can neglect those diffs, a human readable diff will be more prefered.

Is there a way to work around, or I missed something ?

**Comment by tomas-abrahamsson** [comment]
The workaround would be to have only the proto file under vcs control, not the generated file, instead always generate it at build-time.

In general, the layout of the generated code is the way it is in order to exploit as much as possible of the optimizations that the erlang compiler and vm can do. Changing the way it is generated to minimize diff size will most certainly make it slower.

**Comment by suexcxine** [comment]
Thank you for your reply.
