### ISSUE TITLE
Check the backwards compatibility of two schema file

### ISSUE THREAD

**Issue by terry-xiaoyu** [tomas-abrahamsson/gpb#173]
Hi, I am looking for the API for checking backwards compatibility of two version of protobuf schemas, like [this project](https://github.com/igfe/compatibility) does.

Is there one in this project?

**Comment by tomas-abrahamsson** [comment]
I think it would be possible to build such functionality, by processing the structure returned when compiling with [the `to_proto_defs` option](https://hexdocs.pm/gpb/gpb_compile.html#option-to_proto_defs). But I think it would be better to put such functionality in some package that builds on top of gpb, since it might need to integrate with build systems and CI.

**Comment by tomas-abrahamsson** [comment]
Just remembered I've also seen [protolock](https://github.com/nilslice/protolock) which seems similar.

But at the moment, I've no intention to put this into gpb, so I'll be closing this issue.
