### ISSUE TITLE
cannot locate the priv dir for well known types from escript

### ISSUE THREAD

**Issue by galdorjt** [tomas-abrahamsson/gpb#176]
Compiling files from an escript (created with `rebar3 new escript`) fails:

```erlang
{failed_to_locate_privdir,
  {candidate_for_mod_is_no_dir,gpb_compile,
    "<project>/<escript-name>/gpb/priv"}}
```

After some investigation, the problem is that in an escript, `application:get_application(?MODULE)` returns `undefined`, therefore gpb ends up using `code:which(Mod)` which will return some kind of pseudo path in the final escript (which makes sense since escript embeds beam files).

In my case, `filename:dirname(code:which(Mod))` returns `<project>/<escript>/<main-module>/ebin` which does not actually exists, and gpb ends up trying to use `<project>/<escript>/<main-module>/priv` which of course does not exist either. I'm not even sure there is way to include the priv directory of dependencies in an escript.

But there might be a simpler solution: in the current state, `gpb_compile` makes it mandatory to have this priv path in `ensure_include_path_to_wellknown_types`. But we could have an option to ignore this aspect. In our case, we already have a well known type directory used by other proto tools, and it would definitely be better to be able to just provide it with a `i` option, and ignore the gpb priv directory.

What do you think about it ?

**Comment by tomas-abrahamsson** [comment]
Did you try the `bin/protoc-erl` or was it not useful for some reason? (Curious question: how did you go about creating the escript, by the way? Just `rebar3 escriptize` does not produce something usable, one has to add a function `gpb:main/1` possibly inspired by `bin/protoc-erl`.)

It does seems possible to include priv files in escripts: `{escript_incl_extra, [{"gpb/priv/**/*.proto", "_build/default/lib"}]}` in the rebar.config and then one will have to use `escript:extract` and the `zip` module to read the priv files.

**Comment by galdorjt** [comment]
You can see the code at https://github.com/jobteaser-oss/proto-validator it's open source. The code using gpb starts [here](https://github.com/jobteaser-oss/proto-validator/blob/master/src/proto_validator.erl#L75). We just need to parse Protobuf files to validate various elements according to some of our conventions. With the option my PR added, it seems to work perfectly :)

**Comment by tomas-abrahamsson** [comment]
Ah, I see, you want to use gpb from an escript where gpb has been included as a dependency.

With rebar, it is possible to get also priv dirs included in the zip file that is the escript archive, by using `escript_incl_extra`, as discussed in erlang/rebar3#1936, but it seems gpb would need to do differently when reading those files: using escript:archive and the zip module, instead of normally via file.

Possibly, gpb could be changed to try to auto-detect if run from within an escript archive or not, for example by checking of escript:script_name/0 fails or not, but maybe the ignore option in #177 is just as good. I've just one comment on that one, so I'll head over to it now.

**Comment by galdorjt** [comment]
Thank you!
