### ISSUE TITLE
Syntax keyword is missing in generated msg defs

### ISSUE THREAD

**Issue by jg513** [tomas-abrahamsson/gpb#184]
```protobuf
syntax="proto3";

message Person {
    string name = 1;
    int32 id = 2;
    optional string email = 3;
}
```

Compile the definition with gpb 4.14.0, the `get_msg_defs()` is as following

```erlang
get_msg_defs() ->
    [{{msg, 'Person'},
      [#field{name = name, fnum = 1, rnum = 2, type = string, occurrence = defaulty, opts = []},
       #field{name = id, fnum = 2, rnum = 3, type = int32, occurrence = defaulty, opts = []},
       #field{name = email, fnum = 3, rnum = 4, type = string, occurrence = optional, opts = []}]}].
```

There is no `syntax` or `proto3_msgs` in the defs.

Is there another way to resolve the syntax version?

**Comment by tomas-abrahamsson** [comment]
Do you need the generated codec file or can you use the `to_proto_defs` option, like `gpb_compile:file(... [..., to_proto_defs])` instead?

Hmm, thinking about it, there are actually several elements missing in the return value from `get_msg_defs()` compared to the `to_proto_defs` option.

**Comment by jg513** [comment]
I can get the syntax version with options `[to_proto_defs,{proto_defs_version,2}]`, Thanks.

```erlang
[{proto_defs_version,2},
     {file,{"x","x.proto"}},
     {{msg_containment,"x"},['Person']},
     {{enum_containment,"x"},[]},
     {syntax,"proto3"},
     {{msg,'Person'},
      [{field,name,1,2,string,defaulty,[]},
       {field,id,2,3,int32,defaulty,[]},
       {field,email,3,4,string,optional,[]}]},
     {proto3_msgs,['Person']}]
```

**Comment by tomas-abrahamsson** [comment]
> ... there are actually several elements missing in the return value from `get_msg_defs()` compared to the `to_proto_defs` option.

Just a late FYI: (forgot to write about it earlier) is that since gpb 4.17.0, the new option `introspect_get_proto_defs` will make gpb emit  a `get_proto_defs()` function, instead of a `get_msg_defs()` function, into the generated output module. This `get_proto_defs()` function will return the definitions on the same format as the `gpb_compile:file(...,[...,to_proto_defs])`. The default (for bwd compat) is still to generate a `get_msg_defs()` function, though.

This makes it possible for you to get `syntax` and `proto3_msgs` elements from the generated code, in case you would have any use for it.

(Related to this is also the `{proto_defs_version,N}` option to control the version of the proto defs.)
