### ISSUE TITLE
Hitting `no case clause matching: :group_end` in Elixir app using Exprotobuf/gpb

### ISSUE THREAD

**Issue by yukster** [tomas-abrahamsson/gpb#211]
I'm working on updating an old internal library for RabbitMQ publishing/consuming and there is a test that tries to decode a payload like this: " BAD PAYLOAD".  It crashes with this error:

```
 ** (CaseClauseError) no case clause matching: :group_end
     (gpb 4.18.0) /Users/bmunat/code/dabbit/elixir/deps/gpb/src/gpb.erl:404: :gpb.skip_field/3
     (gpb 4.18.0) /Users/bmunat/code/dabbit/elixir/deps/gpb/src/gpb.erl:395: :gpb.skip_field_or_collect_unknown/5
     (gpb 4.18.0) /Users/bmunat/code/dabbit/elixir/deps/gpb/src/gpb.erl:307: :gpb.decode_field/4
     (exprotobuf 1.2.17) lib/exprotobuf/decoder.ex:30: Protobuf.Decoder.decode/2
```

Digging into the gpb source for the `skip_field/3` function I can confirm that there is no case clause for `group_end`:  https://github.com/tomas-abrahamsson/gpb/blob/master/src/gpb.erl#L403 however the `decode_wiretype` function called in that `case` does include a clause for `group_end`: https://github.com/tomas-abrahamsson/gpb/blob/master/src/gpb.erl#L389

Shouldn't the `case` statement have a clause for `group_end`?

**Comment by tomas-abrahamsson** [comment]
No, a `group_end` element will normally never occur before a `group_start` element if the input binary is well formed. Maybe the question is what should happen if the input binary is not well formed?

**Comment by yukster** [comment]
Thanks for the reply! I'm still getting up to speed on protobuf and amqp so it's quite possible that this test is faulty. I only opened an issue because it seemed clearly possible that, since `skip_field` calls `decode_wiretype` and 4/group_end is a possible value there, that the case in `skip_field` should handle that, even if it is to just raise. It just seems weird (at least in Elixir world) to let it throw a CaseClauseError. But I can look into making the test more real-world. Thanks again!

**Comment by tomas-abrahamsson** [comment]
Gpb can [generate](https://hexdocs.pm/gpb/gpb_compile.html#file-1) encoding/decoding code for a given set of protobuf definitions, I think this is how most people use it, but it also has an data-driven encoder/decoder, the [`gpb.erl`](https://hexdocs.pm/gpb/gpb.html) module, which it appears `exprotobuf` uses. (It  by dec). Both the generated code and the data-driven `gpb.erl` has the property that it either succeeds doing what it should on valid input, but fail on invalid input. However, the generated code fails with either a `{gpb_error,Reason}` or `{gpb_type_error,Reason}`, while the data-driven `gpb.erl` may crash with any reason, a function or case clause for instance, as you have seen.

I could (and think it would make sense) wrap the data-driven encoder/decoder in `gpb.erl` in some top-level try catch to make sure it, too, crashes with the same kind of `gpb_error`s that the generated code uses. So, the gpb would still crash on `<<" BAD PAYLOAD">>` but it with a `{gpb_error, ...}` instead of with a `case_clause`.

Most development work has gone into the code generator, and I've kept the data-driven encoder/decoder so far for what I thought was mostly internal reasons, but now I know it is used by others as well.

So I guess the bottom line when it comes to your part is that if you get some bad payload and feed it eventually into gpb for decoding, what you can rely on is that if it is *some* crash, then it was invalid input, but you should not rely on the exact crash term. Also, I don't know if exprotobuf wraps this in some way, but from the stacktrace, it appears that it does not. On the other hand, if there is *no* crash, it does not necessarily mean that the input was valid. You could for instance have decided that exacly one of two optional fields must be set, but if none of them is set, gpb will happily decode. For generated code, there is the [`verify_decode_required_present`](https://hexdocs.pm/gpb/gpb_compile.html#option-verify_decode_required_present) option, but this is not present with the data-driven `gpb.erl` (no such options are).

**Comment by yukster** [comment]
@tomas-abrahamsson thanks for the detailed explanation. I see what you mean about code intending to be internal vs external. And this test isn't very realistic either. I doubt we would actually hit this in live code. But the top-level wrapper to translate core errors into library-specific errors does seem like a great idea. @bitwalker for viz on the exprotobuf part...

**Comment by tomas-abrahamsson** [comment]
> But the top-level wrapper to translate core errors into library-specific errors does seem like a great idea.

I'll look into doing it.

**Comment by tomas-abrahamsson** [comment]
Is the (temporary) branch `gpb_error-for-gpb` in line with what you had in mind? If so, I can merge it together with a few other very minor things that I have pending.

**Comment by yukster** [comment]
Well my erlang knowledge is very slim but this seems like the right idea: wrapping the group_end failure in a gpb_error. Hopefully you can get some erlangist eyes on it though. Thanks!

**Comment by tomas-abrahamsson** [comment]
I've pushed gpb 4.19.0 which wraps errors in `{gpb_error, Info}`, so I'll close this.

For the archives, I'll note that this change concerns the data-driven encoder/decoder in the `gpb` module. The wrapping has been present in the generated code already since 3.28.1. (I'll remove the temporary branch shortly)
