### ISSUE TITLE
+-Inf, NaN support

### ISSUE THREAD

**Issue by deadtrickster** [tomas-abrahamsson/gpb#62]
Hey thank you for wonderful lib. I noticed dpb currently doesn't support +Infinity -Infinity and NaN. How about stealing from here https://github.com/basho/erlang_protobuffs/blob/d8969a2a0312be7d9db29fcdd2fdfe287c090911/src/protobuffs.erl#L160 ? 

I can throw PR if you'd like

**Comment by tomas-abrahamsson** [comment]
Using the atoms `infinity`, `'-infinity'` and `nan` to represent these values. Sounds reasonable, I'll give it a go.

(Observation: Good thing is `infinity` > _the largest float,_ since `atom()` > `number()` in Erlang, but unfortunately that also means that `'-infinity'` is greater than any float, but such is life, I guess :) )

(In case anyone else would come across this issue later on, and wonder: it is not possble to represent +inf, -inf or nan in erlang. see for example http://erlang.org/pipermail/erlang-questions/2012-February/064714.html)

**Comment by tomas-abrahamsson** [comment]
The 3.22.4, (just pushed), should add the needed support for ±Infinity and NaN, please try it out!

**Comment by deadtrickster** [comment]
Hey can you please replace `is_float` with
 `is_number`( or add `is_integer` branch) guard here: https://github.com/tomas-abrahamsson/gpb/blob/master/src/gpb_compile.erl#L2131 and here: https://github.com/tomas-abrahamsson/gpb/blob/master/src/gpb_compile.erl#L2150. The old code worked with just integers too.

**Comment by tomas-abrahamsson** [comment]
Right you are, well spotted, thanks for notifying. Fixed in 3.22.5, just pushed. Includes an eunit test for it too, so I won't forget about it in the future.

**Comment by deadtrickster** [comment]
hurray! all my tests passed too. I'll notify rebar3_gpb_plugin author now. Thank you so much!

**Comment by tomas-abrahamsson** [comment]
... and that reminded me to push to hex.pm, thanks! (I have a check for that, but it would have taken a bit longer for that to trigger)
