### ISSUE TITLE
xref warnings for unused functions

### ISSUE THREAD

**Issue by tsloughter** [tomas-abrahamsson/gpb#89]
While gpb rightly adds a few lines like `-compile({nowarn_unused_function,cons/3}).` to modules it generates, xref still warns about these unused local functions. I think just adding:

```
-ignore_xref([id/2, cons/3, lists_reverse/2, 'erlang_++'/3]).
```

To the top of the generated modules would resolve this.

**Comment by tomas-abrahamsson** [comment]
Thanks, I did not know about the `-ignore_xref` attribute. Will look into this.

**Comment by tomas-abrahamsson** [comment]
Hmm... are you sure about the `-ignore_xref` attribute? I could not find anything about it neither in the docs nor in the source (looking at a slightly post-19.0 git tree of otp). Also tried it, but could not get it to work. (tried `-ignore_xref(...)` as you wrote, and also some variations like `-xref({ignore,[id/2,...])` and `-xref({ignore,id/2})`)

After taking a peek into the `xref_reader.erl`, I got the following to work: `-xref({encode_msg/2,id/2}).` ie inserting a "fake" call edge from some known-to-exist function (`encode_msg/2`) to `id/2`. It appears to work, but I don't want to go this route, since it seems [kludgy,](https://en.wikipedia.org/wiki/Kludge) the `-xref` attribute is experimental, and undocumented, so it could stop working away any time.

Will instead try to move forward by not generating unused functions, though the calculations for when they're needed are probably going to be a bit messy (I think) so might take a little time. Alternative ways such as marking helpers for use and generate only marked helpers might be a bit awkward too, due to the way the code is structured a the moment.

**Comment by tsloughter** [comment]
Ah, crap, `-ignore_xref` is part of rebar not xref...

**Comment by tomas-abrahamsson** [comment]
Ah, I see

**Comment by tomas-abrahamsson** [comment]
Hi, in just-pushed 3.26.1, only the actually used helper functions are included in the generated module, fixing this issue (closing).
