### ISSUE TITLE
including gpb as dependency in erlang.mk, fails relx when generating a release

### ISSUE THREAD

**Issue by orotemo** [tomas-abrahamsson/gpb#94]
the usual erlang.mk build process

```
wget https://erlang.mk/erlang.mk
make -f erlang.mk bootstrap-rel
make -f erlang.mk new-app in=an_app
```

Then create a Makefile in the root dir:

```
LOCAL_DEPS = an_app
TEST_DEPS = sync meck

include erlang.mk
```

and in the new app (named 'an_app') `apps/an_app/Makefile`:

```
PROJECT = an_app
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.0.1

DEPS += gpb

include ../../erlang.mk
```

run make, and it fails. the relx.

Didn't quite get to the root of the problem. sorry about that.

**Comment by lukebakken** [comment]
Which version of erlang are you using?

**Comment by lukebakken** [comment]
I'm using 19.1 and getting the following `relx` error, which appears to be the same as described in erlware/relx#52

[gpb-94-make.txt](https://github.com/tomas-abrahamsson/gpb/files/542127/gpb-94-make.txt)

**Comment by tomas-abrahamsson** [comment]
@orotemo, did you get the same error as @lukebakken? If so, it seems the `vsn` in `ebin/gpb.app` does not get correctly substituted (not at all) when created from `src/gpb.app.src`. Will take a look.

**Comment by orotemo** [comment]
@tomas-abrahamsson yes! Thanks.

**Comment by tomas-abrahamsson** [comment]
Hmm.. preliminary diagnosis, it looks like (a) erlang.mk builds gpb on its own instead of using deps/gpb/Makefile or rebar, and (b) does does not support the `{vsn,{cmd,Cmd}}` format that [gpb uses](https://github.com/tomas-abrahamsson/gpb/blob/3.26.2/src/gpb.app.src#L24) and  [rebar supports](https://github.com/rebar/rebar/blob/576e121/src/rebar_utils.erl#L658L659) (as does [`deps/gpb/Makefile`](https://github.com/tomas-abrahamsson/gpb/blob/3.26.2/Makefile#L312))

I've yet to dig into (a).

This leads to the `{cmd,Cmd}` landing unmodified as `vsn` value into `deps/gpb/gpb.app`, which subsequently---and rightfully, I think---leads to problems when relx sees this.

Don't have any solution yet, though.. (Many Thanks for complete steps to recreate the issue!)

**Comment by lukebakken** [comment]
Adding `NO_AUTOPATCH` will cause `erlang.mk` to use the `Makefile` from `gpb`:

https://github.com/lukebakken/gpb_94/blob/master/Makefile#L5

However, I don't see any of the `gpb` build output in `_rel`.

**Comment by lukebakken** [comment]
If I add `gpb` to `DEPS` in the top-level `Makefile`, the `_rel` dir does contain the correct output.

 [Top level `Makefile` change.](https://github.com/lukebakken/gpb_94/blob/master/Makefile#L5-L6)

Output:

```
$ ll _rel/gpb_94_release/lib/gpb
gpb-3.26.3/   gpb_94-0.0.1/ 

$ ll _rel/gpb_94_release/lib/gpb-3.26.3/
total 24
drwxr-xr-x 6 lbakken lbakken 4096 Oct 20 14:38 .
drwxr-xr-x 6 lbakken lbakken 4096 Oct 20 14:38 ..
drwxr-xr-x 2 lbakken lbakken 4096 Oct 20 14:38 ebin
drwxr-xr-x 2 lbakken lbakken 4096 Oct 20 14:38 include
drwxr-xr-x 3 lbakken lbakken 4096 Oct 20 14:38 priv
drwxr-xr-x 2 lbakken lbakken 4096 Oct 20 14:38 src
```

**Comment by tomas-abrahamsson** [comment]
Thanks @lukebakken for digging further!

So one need `DEPS += gpb` twice, both in `apps/an_app/Makefile` in the top level `Makefile`, and in the top level, one also needs `NO_AUTOPATCH += gpb`.   Is this double need of `DEPS += gpb` common procedure with relx and erlang.mk to get deps into the release or does it need to be addressed somehow? (I don't know; I haven't done this a lot)

**Comment by lukebakken** [comment]
I really don't know, myself. I've only used `erlang.mk` for basic projects.

It appears you can remove `DEPS` from `apps/an_app/Makefile` and the build succeeds. I'm not sure if it would work if you have code in `an_app` that depends on `gpb`, however.

**Comment by tomas-abrahamsson** [comment]
@orotemo do you think the solution by @lukebakken works well enough?

**Comment by orotemo** [comment]
@tomas-abrahamsson @lukebakken: sorry for taking so long, and thank you. I did not manage with this solution. anyway, maybe for @essen this is just a short look to help us understand what needs to change to resolve this.

**Comment by essen** [comment]
The vsn not being supported is a known issue. The double DEPS is more surprising and sounds like a bug in Erlang.mk.

**Comment by tomas-abrahamsson** [comment]
How should we move forward on this?

Regarding double DEPS, should be continued as an issue on Erlang.mk?

Regarding `vsn`, I suppose `NO_AUTOPATCH += gpb` is ok for you, @orotemo? From a gpb point-of-view this would be preferrable, so that all of gpb builds.

**Comment by essen** [comment]
Actually I think I see the problem. Autopatch should not run, yet it does because it sees rebar on the following line: https://github.com/tomas-abrahamsson/gpb/blob/master/Makefile#L125

But since rebar is not used, and you don't do anything special with dependencies, we have no reason to run autopatch. I have to fix Erlang.mk to ignore comments when looking for rebar usage.

**Comment by tomas-abrahamsson** [comment]
Ok, I see. I'll be more or less offline for a few days from now, but rephrasing is quick, so should it still be needed by then, I'll do that.

**Comment by essen** [comment]
Oddly enough Erlang doesn't care if the `vsn` key is a tuple when loading the application. That's why it wasn't detected in the nightly build.

The fix is in, you can close this: https://github.com/ninenines/erlang.mk/commit/73bcb8bb587897f8ebec93d0a10fafaf6a89ba7a

Thanks!

**Comment by tomas-abrahamsson** [comment]
Excellent! Closing. @orotemo, should anything surface, just reopen or open a new.
