### ISSUE TITLE
Generate types and type declarations for record fields

### ISSUE THREAD

**Issue by JeetKunDoug** [tomas-abrahamsson/gpb#98]
Attempting to use GPB and Dialyzer together, and finding that the untyped fields in records (especially when records are nested) can cause issues where Dialyzer assumes values in those fields can be `any()` when it's clear that it should be a nested record, or a number, or .... GPB already _knows_ this (as it even emits documentation for all the types).

It would be great if it were possible to do two things:
1) For each record type defined, also define and export a _type_ for that record.
2) For any field in a record, also include type information for that field.

**Comment by lukebakken** [comment]
It looks like #34 implemented at least some of this, but I'm not sure why we're not seeing `-export_type` in files like [this one](https://github.com/basho/riak_pb/blob/features/lrb/use-gpb/src/riak_pb.erl)

**Comment by lukebakken** [comment]
@JeetKunDoug  - I found the option [here](https://github.com/tomas-abrahamsson/gpb/blob/master/src/gpb_compile.erl#L1221-L1222). Giving it a try now.

**Comment by lukebakken** [comment]
Yep, `type_specs` is the correct option. @tomas-abrahamsson I'll open a PR to add that to the README.

**Comment by tomas-abrahamsson** [comment]
> For each record type defined, also define and export a _type_ for that record.

@JeetKunDoug This is done when gpb compiles to use maps instead of records, but for records, I reasoned that one could just use `#msg{}`. I'd like to learn your reasoning for wanting each msg to be an exported type also for the record case?

> For any field in a record, also include type information for that field.

The `type_specs` option does this (or `-type` cmd line flag/switch). Thanks to @lukebakken for providing this info.

@lukebakken, regarding a PR for README, I think the options that could need some highlighting (ie options most missed/overlooked) are:
* `type_specs` (`-type`)
* `use_packages` (`-pkgs`)
* and perhaps `strings_as_binaries` (`-strbin`)

**Comment by lukebakken** [comment]
OK, thanks for the suggestions @tomas-abrahamsson

**Comment by tomas-abrahamsson** [comment]
I assume this means you're ok with the current state, hence closing this issue. If I misunderstood, please just re-open.
